export default {
  Application: {
    textReturnListApp: 'WiltuterugkerennaardeApp-lijst?',
    appKey: 'App-sleutel',
    appName: 'App-naam',
    buildNumber: 'Buildnummer',
    deviceKey: 'Apparaatsleutel',
    notificationId: 'Notificatie-ID',
    deviceName: 'Apparaatnaam',
    osType: 'Besturingssysteemtype',
    sendMail: 'Mailversturen',
    recentlyViewed: 'Recentbekeken',
    createDate: 'Aanmaakdatum',
    searchAppPlaceHolder: 'Zoekapp...',
    invalidAppKey: 'Ongeldigeapp-sleutel',
    enterAppKey: 'Voeruwapp-sleutelin',
    allowRecivePush: 'Toegestaanompushteontvangen',
    userEmail: 'Gebruikersemail',
    deviceInfo: 'Apparaatinformatie',
    fcmToken: 'FCM-token',
    notificationDeviceId: 'NotificatieApparaat-ID',
    apnsToken: 'TokenAPNS',
    switchAppKey: 'WisselApp-sleutel',
    buildText: 'Build',
  },
  User: {
    signIn: 'Inloggen',
    signUp: 'Registreren',
    logOut: 'Log Out',
    buildVersion: 'Build version',
    doYouWantToLogOut: 'Wiltuuitloggen?',
    guestCheckout: 'Gastafrekening',
    dontHaveAccount: "Don'"Geenaccount?"'Forgot your password?',
    invalidAccount: 'Degebruikersnaamen/ofwachtwoordisongeldig',
    deleteAccount: 'Accountverwijderen',
    deleteSuccess: 'Accountsuccesvolverwijderd',
    userSorry: 'Hetspijtonsdatjevertrekt.Alsjejeaccountverwijdert',
    loseAccess: 'Jeverliestdetoegangtotjeaankoopgeschiedenis',
    loseAllData: 'Jeverliestallegegevensgeassocieerdmetdeapp',
    ableAccess: "You won'"Jekuntnietmeerbijjeverlanglijst"'Fill in the following information to delete your accounts',
    takeSomeTime:
      'Since this process is manual, it might take some time for your account to be deleted',
    confirmTitle:
      "Are you sure want to delete your account? (This can't be undone)",
    contentDelete:
      'Your account deletion request has been submitted and will be proceeded within a few working days. \n' +
      '\n' +
      'You will be informed as soon as the process is completed. If you change your mind, you can always come back and open a new account with us',
    contentForgotPassword:
      "Please let us know your email address you used to login and we'll send you an email with instructions",
  },
  Home: {},
  Catalog: {
    noCatalog: 'Geencatalogus',
    shopAll: 'Shopalle',
  },
  Product: {
    textOutOfStock: 'Sorry',
    outOfStock: 'Uitvoorraad',
    addToCart: 'Inwinkelwagen',
    textUpdated: 'Bijgewerkt',
    noProduct: 'GeenProduct',
    showPrice: 'Toonprijs',
    exceedMaxProductQty:
      'You can only have "{{qty}}" of "{{productName}}" in your cart',
    item: 'Artikel',
    items: 'Artikelen',
    addedToCart: 'Inwinkelwagen',
    textOf: 'Van',
    textOpp: 'Oeps!',
    textNoLogin:
      "Looks like you're not logged in, sign in to save products to your favorites",
    freeShipping: 'Gratisverzending',
    inStock: 'Opvoorraad{{inventory}}',
  },
  Search: {
    placeHolder: 'Zoekproducten',
    noRecentSearch: 'Geenrecentezoekopdracht',
    searchHistory: 'Zoekgeschiedenis',
    noItemsFound: 'Geenartikelengevonden',
    categories: 'Categorieën',
    products: 'Producten',
    suggestion: 'Suggestie',
    seeAllResults: 'Bekijkalleresultaten',
    search: 'Zoeken',
  },
  Cart: {
    subTotal: 'Subtotaal',
    shipping: 'Verzending',
    tax: 'Belasting',
    discount: 'Korting',
    textCheckOut: 'Afrekenen',
    emptyCart: 'Uwwinkelwagenisleeg',
    invalidCoupon: 'OngeldigeCoupon',
    coupons: 'Couponcode',
    deleteProduct: 'Productverwijderen',
    textAdd: 'Toevoegen',
    textTypeVoucher: 'Voercouponcodein',
    couponDiscount: 'Korting',
    grandTotal: 'Totaalbedrag',
    selectVoucher: 'CouponCode',
    total: 'Totaal',
    apply: 'Toepassen',
  },
  Wishlist: {
    itemAddedToWatchList: 'Artikelistoegevoegdaanjeverlanglijst',
  },
  Review: {
    textWriteReview: 'Schrijfeenbeoordeling',
    textBeFirstReview: 'Weesdeeersteomditproducttebeoordelen',
    writeReview: 'Beoordelingschrijven',
    titleReviewAlert: 'Beoordelingingediend',
    topReviews: 'Topbeoordeling',
    viewAll: 'Bekijkalles',
    reviewSingle: '(1beoordeling)',
    reviewMultiple: '({{count}}beoordelingen)',
    name: 'Naam',
    email: 'E-mail',
    reviewSubject: 'Beoordelingonderwerp',
    comments: 'Opmerkingen',
    allReview: 'Allebeoordelingen',
    reviewSubmitted: 'Uwbeoordelingissuccesvolingediend.',
    warningReviewBack: 'Weetjehetzeker?Alleniet-opgeslagenwijzigingengaanverloren',
    warningRateItem: 'Hoebeoordeeltuditartikel?',
  },
  Order: {
    orderDate: 'Besteldatum',
    orderNum: 'Bestel#',
    orderID: 'BestelID:#{{id}}',
    status: 'Status',
    sku: 'SKU',
    noOrder: 'Uheeftgeenbestellingen',
    viewDetails: 'Bekijkdetails',
    shippingDetails: 'Verzenddetails',
    billingDetails: 'Factuuradres',
    shippingMethod: 'Verzendmethode',
    paymentMethod: 'Betaalmethode',
    orderAgain: 'Bestelopnieuw',
    warningMessage:
      'Some products are invalid so they cannot be added to the shopping cart.',
    errorMessage:
      'All products in this order are invalid so they cannot be added to the shopping cart.',
  },
  ThankYouPage: {
    content: 'Bedanktvoorhetwinkelenbijons.',
    infoContent:
      'You will receive an order confirmation email with details of your order and a link to track its progress',
    viewOrder: 'Bekijkbestelgegevens',
    backToHome: 'Terugnaarhuis',
  },
  Address: {
    noAddress: 'Geenadres',
    aboveModalConfirm: 'Alleniet-opgeslagenwijzigingengaanverloren',
    belowModalConfirm: 'Wiltudoorgaan?',
    saveChange: 'Wijzigingenopslaan',
    selectCountry: 'Landselecteren',
  },
  Filter: {
    Show_All: 'Toonalles',
    Pending: 'Inbehandeling',
    Cancelled: 'Geannuleerd',
    Shipped: 'Verzonden',
    filterBy: 'Filterenop',
    clearAll: 'Wisalles',
  },
  Sort: {
    Newest_First: 'Nieuwsteeerst',
    Oldest_First: 'Oudsteeerst',
    Lowest_Price_First: 'Laagsteprijseerst',
    Highest_Price_First: 'Hoogsteprijseerst',
    lowToHigh: 'Laagnaarhoog',
    highToLow: 'Hoognaarlaag',
    ascending: 'Oplopend',
    descending: 'Aflopend',
    titleSort: 'Sorteer&Filter',
    resetAll: 'Allesopnieuwinstellen',
    sortBy: 'SORTERENOP',
    reset: 'Opnieuwinstellen',
    sortToolBar: 'Sorteren',
  },
  Modal: {
    titleModalRate: 'Beoordeel{{appName}}',
    remindMeLater: 'Herinnermelater',
    rateNow: 'Beoordeelnu',
    noThanks: 'Nee',
    contentModalRate:
      'Would you mind taking a moment to rate {{appName}}? Thanks for your time and support!',
    titleSubjectMail: 'Apparaatinformatievoorprobleemoplossing',
    warningRemoveAddress: 'Wiltuditadresverwijderen?',
    warningRemoveWishList:
      'Do you want to remove this item from your wishlist?',
    warningRemoveShoppingCart:
      'Do you want to remove this item from your shopping bag?',
    warningRemoveProduct: 'Wiltuhetproductverwijderen?',
    //  TODO: Alert Text
    textNo: 'Nee',
    textYes: 'Ja',
    textOK: 'OK',
    textClose: 'Sluiten',
    textConfirm: 'Bevestigen',
    textContinue: 'Doorgaan',
    textDone: 'Klaar',
    textDelete: 'Verwijderen',
    textCancel: 'Annuleren',
  },
  Forms: {
    inputText: 'Invoertekst',
    requireFields: 'Vulalleverplichteveldenin',
    requireField: 'Verplichtveld',
    register: 'Registreren',
    errorRequired: '{{label}}isvereist',
    invalidEmail: 'Ongeldige-mailadres',
    invalidFirstname: 'Ongeldigevoornaam',
    invalidLastname: 'Ongeldigeachternaam',
    invalidConfirmPassword: 'Komtnietovereenmetwachtwoord',
    emailFormHint: 'Voereengeldige-mailadresin',
    invalidConfirmEmail: 'Voerdezelfdewaardeopnieuwin',
    invalidPassword:
      'Ongeldigwachtwoord',
    send: 'Verzenden',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    emailAddress: 'E-mailadres',
    confirmPassword: 'Bevestigwachtwoord',
    generalInfo: 'Algemeneinformatie',
    yourEmailAddress: 'Uwe-mailadres',
    enterYourPassword: 'Voereenwachtwoordin',
    enterValidEmail: 'Voereengeldige-mailadresin',
    minCharacters: 'Min8tekens',
    yourPassword: 'Jouwwachtwoord',
    select: 'Selecteer',
  },
  Header: {
    headerRegister: 'Maakeennieuwaccountaan',
    headerMyOrder: 'Mijnbestellingen',
    headerOrderDetails: 'Besteldetails',
    headerShoppingCart: 'Winkelwagen',
    headerEditAddress: 'Adresbewerken',
    headerNewAddress: 'Nieuwadres',
    headerWishList: 'Mijnverlanglijst',
    headerNotifications: 'Notificaties',
    headerDetail: 'Details',
    headerLocale: 'Selecteeruwtaalenvaluta',
    headerCountry: 'Selecteeruwland',
    headerLanguage: 'Kiesuwtaal',
    headerSignUp: 'Accountaanmaken',
  },
  Notification: {
    noNotification: 'Geennotificaties',
  },
  ErrMsg: {
    titleErr: 'Fout',
    noConnect: 'Geeninternetverbinding',
    plsTryAgain: 'Probeerhetopnieuw.',
    cantFindWay: "Can'"Kangeenweghiervinden."'Please match the requested format',
    minOrder:
      'The minimum quantity allowed for purchase is {{minOrderQuantity}}',
    maxOrder:
      'The maximum quantity allowed for purchase is {{maxOrderQuantity}}',
    errRegisterAppKey: 'Registratievanapp-sleutel{{appKey}}mislukt',
    invalidOrderId: 'OngeldigorderIdverstrekt',
  },
};
