export default {
  Application: {
    textReturnListApp: 'Wilt u terugkeren naar de app-lijst?',
    appKey: 'App-sleutel',
    appName: 'App name',
    buildNumber: 'Build number',
    deviceKey: 'Device key',
    notificationId: 'Notification ID',
    deviceName: 'Device name',
    osType: 'OS type',
    allowRecivedPush: 'Allowed to receive push',
    sendMail: 'Send Mail',
    recentlyViewed: 'Recently Viewed',
    createDate: 'Create date',
    searchAppPlaceHolder: 'Search app...',
    invalidAppKey: 'INVALID APP KEY',
    enterAppKey: 'Please enter your app key',
    allowRecivePush: 'Allowed to receive push',
    userEmail: 'User email',
    deviceInfo: 'Device Info',
    fcmToken: 'FCM Token',
    notificationDeviceId: 'Notification Device ID',
    apnsToken: 'Token APNS',
    switchAppKey: 'Switch App Key',
    buildText: 'Build',
  },
  User: {
    signIn: 'Sign in',
    signUp: 'Sign up',
    logOut: 'Log Out',
    buildVersion: 'Build version',
    doYouWantToLogOut: 'Do you want to log out?',
    guestCheckout: 'Guest Checkout',
    dontHaveAccount: "Don't have an account?",
    forgotPassWord: 'Forgot your password?',
    invalidAccount: 'The username and/or password is invalid',
    deleteAccount: 'Delete Account',
    deleteSuccess: 'Account deleted successfully',
    userSorry: 'We are sorry to see you leave If you delete your account',
    loseAccess: 'You will lose access to your purchase history',
    loseAllData: 'You will lose all data associated with the app',
    ableAccess: "You won't be able to access your wishlist Delete Account",
    followingInformation:
      'Fill in the following information to delete your accounts',
    takeSomeTime:
      'Since this process is manual, it might take some time for your account to be deleted',
    confirmTitle:
      "Are you sure want to delete your account? (This can't be undone)",
    contentDelete:
      'Your account deletion request has been submitted and will be proceeded within a few working days. \n' +
      '\n' +
      'You will be informed as soon as the process is completed. If you change your mind, you can always come back and open a new account with us',
    contentForgotPassword:
      "Please let us know your email address you used to login and we'll send you an email with instructions",
  },
  Home: {},
  Catalog: {
    noCatalog: 'No catalog',
    shopAll: 'Shop all',
  },
  Product: {
    textOutOfStock: 'Sorry',
    outOfStock: 'Out of Stock',
    addToCart: 'Add to cart',
    textUpdated: 'Updated',
    noProduct: 'No Product',
    showPrice: 'Show Price',
    exceedMaxProductQty:
      'You can only have "{{qty}}" of "{{productName}}" in your cart',
    item: 'item',
    items: 'items',
    addedToCart: 'Added to cart',
    textOf: 'of',
    textOpp: 'opp!',
    textNoLogin:
      "Looks like you're not logged in, sign in to save products to your favorites",
    freeShipping: 'Free shipping',
    inStock: 'In stock {{inventory}}',
  },
  Search: {
    placeHolder: 'Search Products',
    noRecentSearch: 'No Recent Search',
    searchHistory: 'Search History',
    noItemsFound: 'No items found',
    categories: 'Categories',
    products: 'Products',
    suggestion: 'Suggestion',
    seeAllResults: 'See all results',
    search: 'Search',
  },
  Cart: {
    subTotal: 'Subtotal',
    shipping: 'Shipping',
    tax: 'Sales Tax',
    discount: 'Discount',
    textCheckOut: 'Checkout',
    emptyCart: ' Your shopping bag is empty',
    invalidCoupon: 'Invalid Coupon',
    coupons: 'Coupons',
    deleteProduct: 'Delete Product',
    textAdd: 'Add',
    textTypeVoucher: 'Type voucher',
    couponDiscount: 'Coupon Discount',
    grandTotal: 'Grand Total',
    selectVoucher: 'Select Voucher',
    total: 'Total',
    apply: 'Apply',
  },
  Wishlist: {
    itemAddedToWatchList: 'Item is added into your wishlist',
  },
  Review: {
    textWriteReview: 'Write a review',
    textBeFirstReview: 'Be the first to review this product',
    writeReview: 'Write Review',
    titleReviewAlert: 'Review Submitted',
    topReviews: 'Top review',
    viewAll: 'View all',
    reviewSingle: '(1 review)',
    reviewMultiple: '({{count}} reviews)',
    name: 'Name',
    email: 'Email',
    reviewSubject: 'Review subject',
    comments: 'Comments',
    allReview: 'All review',
    reviewSubmitted: 'Your review is submitted successfully.',
    warningReviewBack: 'Are you sure? All unsaved changes will be lost',
    warningRateItem: 'How would you rate this item?',
  },
  Order: {
    orderDate: 'Order Date',
    orderNum: 'Order #',
    orderID: 'Order ID: #{{id}}',
    status: 'Status',
    sku: 'SKU',
    noOrder: 'You don’t have any orders',
    viewDetails: 'View Details',
    shippingDetails: 'Shipping Details',
    billingDetails: 'Billing Address',
    shippingMethod: 'Shipping Method',
    paymentMethod: 'Payment Method',
    orderAgain: 'Order Again',
    warningMessage:
      'Some products are invalid so they cannot be added to the shopping cart.',
    errorMessage:
      'All products in this order are invalid so they cannot be added to the shopping cart.',
  },
  ThankYouPage: {
    content: 'Thanks for shopping with us.',
    infoContent:
      'You will receive an order confirmation email with details of your order and a link to track its progress',
    viewOrder: 'View Order Details',
    backToHome: 'Back to Home',
  },
  Address: {
    noAddress: 'No Address',
    aboveModalConfirm: 'Any unsaved changes will be lost',
    belowModalConfirm: 'Do you want to proceed?',
    saveChange: 'Save Changes',
    selectCountry: 'Select Country',
  },
  Filter: {
    Show_All: 'Show All',
    Pending: 'Pending',
    Cancelled: 'Cancelled',
    Shipped: 'Shipped',
    filterBy: 'Filter by',
    clearAll: 'Clear All',
  },
  Sort: {
    Newest_First: 'Newest First',
    Oldest_First: 'Oldest First',
    Lowest_Price_First: 'Lowest Price First',
    Highest_Price_First: 'Highest Price First',
    lowToHigh: 'Low To High',
    highToLow: 'High To Low',
    ascending: 'Ascending',
    descending: 'Descending',
    titleSort: 'Sort & Filter',
    resetAll: 'Reset All',
    sortBy: 'SORT BY',
    reset: 'Reset',
    sortToolBar: 'Sort',
  },
  Modal: {
    titleModalRate: 'Rate {{appName}}',
    remindMeLater: 'Remind me later',
    rateNow: 'Rate now',
    noThanks: 'No',
    contentModalRate:
      'Would you mind taking a moment to rate {{appName}}? Thanks for your time and support!',
    titleSubjectMail: 'Device info for troubleshooting problem',
    warningRemoveAddress: 'Do you want to remove this address?',
    warningRemoveWishList:
      'Do you want to remove this item from your wishlist?',
    warningRemoveShoppingCart:
      'Do you want to remove this item from your shopping bag?',
    warningRemoveProduct: 'Do you want to delete the product?',
    //  TODO: Alert Text
    textNo: 'No',
    textYes: 'Yes',
    textOK: 'OK',
    textClose: 'Close',
    textConfirm: 'Confirm',
    textContinue: 'Continue',
    textDone: 'Done',
    textDelete: 'Delete',
    textCancel: 'Cancel',
  },
  Forms: {
    inputText: 'Input text',
    requireFields: 'Please fill in all required fields',
    requireField: 'Required field',
    register: 'Register',
    errorRequired: '{{label}} is required',
    invalidEmail: 'Invalid email address',
    invalidFirstname: 'Invalid First Name',
    invalidLastname: 'Invalid Last Name',
    invalidConfirmPassword: 'Does not match password',
    emailFormHint: 'Please enter a valid email address',
    invalidConfirmEmail: 'Please enter the same value again',
    invalidPassword:
      'Passwords must be at least 7 characters and contain: lower case letters, upper case letters, at least 1 number, at least 1 special character',
    send: 'Send',
    firstName: 'First Name',
    lastName: 'Last Name',
    emailAddress: 'Email Address',
    confirmPassword: 'Confirm Password',
    generalInfo: 'General information',
    yourEmailAddress: 'Your email address',
    enterYourPassword: 'Enter a password',
    enterValidEmail: 'Enter a valid email',
    minCharacters: 'Min 8 characters',
    yourPassword: 'Your password',
    select: 'Select',
  },
  Header: {
    headerRegister: 'Create new account',
    headerMyOrder: 'My Orders',
    headerOrderDetails: 'Order Details',
    headerShoppingCart: 'Cart',
    headerEditAddress: 'Edit Address',
    headerNewAddress: 'New Address',
    headerWishList: 'My Wishlist',
    headerNotifications: 'Notifications',
    headerDetail: 'Details',
    headerLocale: 'Select your language and currency',
    headerCountry: 'Select your country',
    headerLanguage: 'Select your language',
    headerSignUp: 'Create Account',
  },
  Notification: {
    noNotification: 'No Notifications',
  },
  ErrMsg: {
    titleErr: 'Error',
    noConnect: 'No internet connection',
    plsTryAgain: 'Please try again.',
    cantFindWay: "Can't find a way here.",
    matchField: 'Please match the requested format',
    minOrder:
      'The minimum quantity allowed for purchase is {{minOrderQuantity}}',
    maxOrder:
      'The maximum quantity allowed for purchase is {{maxOrderQuantity}}',
    errRegisterAppKey: 'Register app key {{appKey}} failed',
    invalidOrderId: 'Invalid orderId provided',
  },
};
