export default {
  Application: {
    textReturnListApp: 'Wilt u terugkeren naar de App-lijst?',
    appKey: 'App-sleutel',
    appName: 'App-naam',
    buildNumber: 'Buildnummer',
    deviceKey: 'Apparaatsleutel',
    notificationId: 'Notificatie-ID',
    deviceName: 'Apparaatnaam',
    osType: 'Besturingssysteemtype',
    sendMail: 'Mail versturen',
    recentlyViewed: 'Recent bekeken',
    createDate: 'Aanmaakdatum',
    searchAppPlaceHolder: 'Zoek app...',
    invalidAppKey: 'Ongeldige app-sleutel',
    enterAppKey: 'Voer uw app-sleutel in',
    allowRecivePush: 'Toegestaan om push te ontvangen',
    userEmail: 'Gebruikers e-mail',
    deviceInfo: 'Apparaat informatie',
    fcmToken: 'FCM-token',
    notificationDeviceId: 'Notificatie Apparaat-ID',
    apnsToken: 'Token APNS',
    switchAppKey: 'Wissel App-sleutel',
    buildText: 'Build',
  },
  User: {
    signIn: 'Inloggen',
    signUp: 'Registreren',
    logOut: 'Afmelden',
    buildVersion: 'Build version',
    doYouWantToLogOut: 'Versie bouwen',
    guestCheckout: 'Wil je afmelden?',
    dontHaveAccount: "Don'Gast uitchecken'Forgot your password?',
    invalidAccount: 'Wachtwoord vergeten?',
    deleteAccount: 'Ongeldige gebruikersnaam en/of wachtwoord',
    deleteSuccess: 'Account verwijderen',
    userSorry: 'Account succesvol verwijderd',
    loseAccess: 'Het spijt ons dat je vertrekt. Als je je account verwijdert',
    loseAllData: 'Je verliest de toegang tot je aankoopgeschiedenis',
    ableAccess: "You won'Je verliest alle gegevens geassocieerd met de app'Fill in the following information to delete your accounts',
    takeSomeTime: 'Vul de volgende informatie in om je account te verwijderen',
    confirmTitle: "Are you sure want to delete your account? (This can'Aangezien dit proces handmatig is'Your account deletion request has been submitted and will be proceeded within a few working days. \n' +'\n' +'You will be informed as soon as the process is completed. If you change your mind, you can always come back and open a new account with us',
    contentForgotPassword: "Please let us know your email address you used to login and we'Je accountverwijderingsverzoek is ingediend en wordt binnen enkele werkdagen verwerkt. \n + \n + Je wordt zo snel mogelijk op de hoogte gebracht zodra het proces is voltooid. Als je van gedachten verandert'Geencatalogus',
    shopAll: 'Geen catalogus',
  },
  Product: {
    textOutOfStock: 'Sorry',
    outOfStock: 'Uit voorraad',
    addToCart: 'In winkelwagen',
    textUpdated: 'Bijgewerkt',
    noProduct: 'Geen recente producten',
    showPrice: 'Toon prijs',
    exceedMaxProductQty: 'You can only have "{{qty}}" of "{{productName}}" in your cart',
    item: 'Artikel',
    items: 'Artikelen',
    addedToCart: 'In winkelwagen',
    textOf: 'Van',
    textOpp: 'Oeps!',
    textNoLogin:
      "Looks like you'Het lijkt erop dat je niet bent ingelogd'Gratisverzending',
    inStock: 'Op voorraad',
  },
  Search: {
    placeHolder: 'Producten zoeken',
    noRecentSearch: 'Geen recente zoekopdrachten',
    searchHistory: 'Zoekgeschiedenis',
    noItemsFound: 'Geen items gevonden',
    categories: 'Categorieën',
    products: 'Producten',
    suggestion: 'Suggestie',
    seeAllResults: 'Bekijk alle resultaten',
    search: 'Zoeken',
  },
  Cart: {
    subTotal: 'Subtotaal',
    shipping: 'Verzending',
    tax: 'Belasting',
    discount: 'Korting',
    textCheckOut: 'Afrekenen',
    emptyCart: 'Uw winkelwagen is leeg',
    invalidCoupon: 'Ongeldige Coupon',
    coupons: 'Couponcode',
    deleteProduct: 'Product verwijderen',
    textAdd: 'Toevoegen',
    textTypeVoucher: 'Voer couponcode in',
    couponDiscount: 'Korting',
    grandTotal: 'Totaalbedrag',
    selectVoucher: 'Coupon Code',
    total: 'Totaal',
    apply: 'Toepassen',
  },
  Wishlist: {
    itemAddedToWatchList: 'Artikel is toegevoegd aan je verlanglijst',
  },
  Review: {
    textWriteReview: 'Schrijf een beoordeling',
    textBeFirstReview: 'Wees de eerste om dit product te beoordelen',
    writeReview: 'Beoordelingschrijven',
    titleReviewAlert: 'Beoordeling ingediend',
    topReviews: 'Topbeoordeling',
    viewAll: 'Bekijk alles',
    reviewSingle: '(1 beoordeling)',
    reviewMultiple: '({{count}} beoordelingen)',
    name: 'Naam',
    email: 'E-mail',
    reviewSubject: 'Beoordeling onderwerp',
    comments: 'Opmerkingen',
    allReview: 'Alle beoordelingen',
    reviewSubmitted: 'Uw beoordeling is succesvol ingediend.',
    warningReviewBack: 'Weet je het zeker? Alle niet-opgeslagen wijzigingen gaan verloren',
    warningRateItem: 'Hoe beoordeel je dit artikel?',
  },
  Order: {
    orderDate: 'Besteldatum',
    orderNum: 'Bestel #',
    orderID: 'Bestel ID: #{{id}}',
    status: 'Status',
    sku: 'SKU',
    noOrder: 'U heeft geen bestellingen',
    viewDetails: 'Bekijk details',
    shippingDetails: 'Verzenddetails',
    billingDetails: 'Factuuradres',
    shippingMethod: 'Verzendmethode',
    paymentMethod: 'Betaalmethode',
    orderAgain: 'Bestel opnieuw',
    warningMessage:
      'Sommige producten zijn ongeldig',
    errorMessage:
      'Alle producten in deze bestelling zijn ongeldig',
  },
  ThankYouPage: {
    content: 'Bedankt voor het winkelen bij ons.',
    infoContent:
      'Je ontvangt een bevestigingsmail van je bestelling met details van je bestelling en een link om de voortgang ervan te volgen.',
    viewOrder: 'Bekijk bestelgegevens',
    backToHome: 'Terug naar huis',
  },
  Address: {
    noAddress: 'Geen adres',
    aboveModalConfirm: 'Alle niet-opgeslagen wijzigingen gaan verloren',
    belowModalConfirm: 'Wilt u doorgaan?',
    saveChange: 'Wijzigingen opslaan',
    selectCountry: 'Land selecteren',
  },
  Filter: {
    Show_All: 'Toon alles',
    Pending: 'In behandeling',
    Cancelled: 'Geannuleerd',
    Shipped: 'Verzonden',
    filterBy: 'Filteren op',
    clearAll: 'Wis alles',
  },
  Sort: {
    Newest_First: 'Nieuwste eerst',
    Oldest_First: 'Oudste eerst',
    Lowest_Price_First: 'Laagste prijs eerst',
    Highest_Price_First: 'Hoogste prijs eerst',
    lowToHigh: 'Laag Naar Hoog',
    highToLow: 'Hoog Naar Laag',
    ascending: 'Oplopend',
    descending: 'Aflopend',
    titleSort: 'Sorteer & Filter',
    resetAll: 'Alles opnieuw instellen',
    sortBy: 'SORTEREN OP',
    reset: 'Opnieuw instellen',
    sortToolBar: 'Sorteren',
  },
  Modal: {
    titleModalRate: 'Beoordeel {{appName}}',
    remindMeLater: 'Herinner me later',
    rateNow: 'Beoordeel nu',
    noThanks: 'Nee',
    contentModalRate:
      'Zou je het erg vinden om een moment te nemen om {{appName}} te beoordelen? Bedankt voor je tijd en steun!',
    titleSubjectMail: 'Apparaat informatie voor probleemoplossing',
    warningRemoveAddress: 'Wilt u dit adres verwijderen?',
    warningRemoveWishList:
      'Wil je dit item van je verlanglijst verwijderen?',
    warningRemoveShoppingCart:
      'Wil je dit item uit je winkelwagen verwijderen?',
    warningRemoveProduct: 'Wilt u het product verwijderen?',
    //  TODO: Alert Text
    textNo: 'Nee',
    textYes: 'Ja',
    textOK: 'OK',
    textClose: 'Sluiten',
    textConfirm: 'Bevestigen',
    textContinue: 'Doorgaan',
    textDone: 'Klaar',
    textDelete: 'Verwijderen',
    textCancel: 'Annuleren',
  },
  Forms: {
    inputText: 'Invoertekst',
    requireFields: 'Vul alle verplichte velden in',
    requireField: 'Verplicht veld',
    register: 'Registreren',
    errorRequired: '{{label}} is vereist',
    invalidEmail: 'Ongeldig e-mailadres',
    invalidFirstname: 'Ongeldige voornaam',
    invalidLastname: 'Ongeldige achternaam',
    invalidConfirmPassword: 'Komt niet overeen met wachtwoord',
    emailFormHint: 'Voer een geldig e-mailadres in',
    invalidConfirmEmail: 'Voer dezelfde waarde opnieuw in',
    invalidPassword:
      'Ongeldig wachtwoord',
    send: 'Verzenden',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    emailAddress: 'E-mailadres',
    confirmPassword: 'Bevestig wachtwoord',
    generalInfo: 'Algemene informatie',
    yourEmailAddress: 'Uw e-mailadres',
    enterYourPassword: 'Voer een wachtwoord in',
    enterValidEmail: 'Voer een geldig e-mailadres in',
    minCharacters: 'Min 8 tekens',
    yourPassword: 'Jouw wachtwoord',
    select: 'Selecteer',
  },
  Header: {
    headerRegister: 'Maak een nieuw account aan',
    headerMyOrder: 'Mijn bestellingen',
    headerOrderDetails: 'Bestelgegevens',
    headerShoppingCart: 'Winkelwagen',
    headerEditAddress: 'Adres bewerken',
    headerNewAddress: 'Nieuw adres',
    headerWishList: 'Mijn verlanglijst',
    headerNotifications: 'Notificaties',
    headerDetail: 'Details',
    headerLocale: 'Selecteer uw taal en valuta',
    headerCountry: 'Selecteer uw land',
    headerLanguage: 'Kies uw taal',
    headerSignUp: 'Account aanmaken',
  },
  Notification: {
    noNotification: 'Nog geen meldingen',
  },
  ErrMsg: {
    titleErr: 'Fout',
    noConnect: 'Geen internetverbinding',
    plsTryAgain: 'Probeer het opnieuw.',
    cantFindWay: "Can'Kan hier geen manier vinden.'Please match the requested format',
    minOrder:
      'De minimumhoeveelheid voor aankoop is {{minOrderQuantity}}',
    maxOrder:
      'De maximale hoeveelheid voor aankoop is {{maxOrderQuantity}}',
    errRegisterAppKey: 'Registratie van app-sleutel {{appKey}} mislukt',
    invalidOrderId: 'Ongeldige orderId verstrekt',
  },
};
