export default {
    textReturnListApp: 'Do you want to return to App List?',
    appKey: 'App Key',
    appName: 'App name',
    buildNumber: 'Build number',
    deviceKey: 'Device key',
    notificationId: 'Notification ID',
    deviceName: 'Device name',
    osType: 'OS type',
    sendMail: 'Send Mail',
    recentlyViewed: 'Recently Viewed',
    createDate: 'Create date',
    searchAppPlaceHolder: 'Search app...',
    invalidAppKey: 'INVALID APP KEY',
    enterAppKey: 'Please enter your app key',
    allowRecivePush: 'Allowed to receive push',
    userEmail: 'User email',
    deviceInfo: 'Device Info',
    fcmToken: 'FCM Token',
    notificationDeviceId: 'Notification Device ID',
    apnsToken: 'Token APNS',
    switchAppKey: 'Switch App Key',
    buildText: 'Build',
    signIn: 'Sign in',
    signUp: 'Sign up',
    logOut: 'Log Out',
    doYouWantToLogOut: 'Do you want to log out?',
    guestCheckout: 'Guest Checkout',
    dontHaveAccount: "Don't have an account?",
    forgotPassWord: 'Forgot your password?',
    invalidAccount: 'The username and/or password is invalid',
    deleteAccount: 'Delete Account',
    deleteSuccess: 'Account deleted successfully',
    userSorry: 'We are sorry to see you leave. If you delete your account',
    loseAccess: 'You will lose access to your purchase history',
    loseAllData: 'You will lose all data associated with the app',
    ableAccess: "You won't be able to access your wishlist",
    loginTitle: 'Oh! You are not logged in {{appName}}',
    loginSubTitle: 'Log in now to track and manage your orders',
    signInLabel: 'Welcome to {{appName}}',
    signInSubTitle: 'Sign in now for direct access to your details, orders history, returns and wishlist',
    followingInformation: 'Fill in the following information to delete your accounts',
    takeSomeTime: 'Since this process is manual, it might take some time for your account to be deleted',
    confirmTitle: "Are you sure want to delete your account? (This can't be undone)",
    contentDelete: 'Your account deletion request has been submitted and will be proceeded within a few working days. \n' + '\n' + 'You will be informed as soon as the process is completed. If you change your mind, you can always come back and open a new account with us',
    contentForgotPassword: "Please let us know your email address you used to login and we'll send you an email with instructions",
     oCatalog: 'No catalog',
    shopAll: 'Shop all',
    all: 'All',
    textOutOfStock: 'Sorry, this item is out of stock',
    outOfStock: 'Out of Stock',
    addToCart: 'Add to cart',
    textUpdated: 'Updated',
    noProduct: 'No products available',
    noProductContent: "Let's check out other categories!",
    showPrice: 'Show Price',
    exceedMaxProductQty: 'You can only have "{{qty}}" of "{{productName}}" in your cart',
    item: 'item',
    items: 'items',
    addedToCart: 'Added to cart',
    textOf: 'of',
    textOpp: 'Opps!',
    textNoLogin: "Looks like you're not logged in, sign in to save products to your favorites",
    freeShipping: 'Free shipping',
    buyNow: 'Buy Now',
    selectVariant: 'Select variant',
    quantity: 'Quantity',
    weight: 'Weight',
    width: 'Width',
    height: 'Height',
    depth: 'Depth',
    upc: 'UPC',
    orderQuantityMinimum: 'Minimum Purchase Quantity',
    orderQuantityMaximum: 'Maximum Purchase Quantity',
    manufacturePartNumber: 'Manufacturer Part Number(MPN)',
    globalTradeItemNumber: 'Global Trade Item Number (GTIN)',
    binPickingNumber: 'Bin Picking Number (BPN)',
    inStock: 'In stock',
    highStockMessage: '{{inventory}} in stock',
    lowStockMessage: 'Only {{inventory}} left',
     placeHolder: 'Search Products',
    noRecentSearch: 'No Recent Search',
    noRecentSearchContent: 'Your recent searches will show up here',
    searchHistory: 'Search History',
    noItemsFound: 'No items found',
    noItemsFoundContent: 'Adjust your search and try again',
    categories: 'Categories',
    products: 'Products',
    seeAllResults: 'See all results',
    search: 'Search',
    subTotal: 'Subtotal',
    shipping: 'Shipping',
    tax: 'Tax',
    discount: 'Discount',
    textCheckOut: 'Checkout',
    emptyCart: 'Your cart is empty',
    emptyCartContent: "Let's go buy something!",
    invalidCoupon: 'Invalid Coupon',
    coupons: 'Coupon Code',
    deleteProduct: 'Delete Product',
    textAdd: 'Add',
    textTypeVoucher: 'Enter coupon code',
    couponDiscount: 'Discount',
    grandTotal: 'Grand Total',
    selectVoucher: 'Coupon Code',
    total: 'Total',
    apply: 'Apply',
    noCoupon: 'No coupons',
    itemAddedToWatchList: 'Item is added into your wishlist',
    emptyWishlist: 'Your wishlist is empty',
    emptyWishlistContent: 'Tap the heart icon to save your favorites',
    loginWarning: "Looks like you're not logged in, sign in to save your favorites",
    textWriteReview: 'Write a review',
    textBeFirstReview: 'Be the first to review this product',
    titleReviewAlert: 'Review Submitted',
    topReviews: 'Top review',
    viewAll: 'View all',
    reviewSingle: '(1 review)',
    reviewMultiple: '({{count}} reviews)',
    name: 'Name',
    email: 'Email',
    reviewSubject: 'Review subject',
    comments: 'Comments',
    allReview: 'All review',
    reviewSubmitted: 'Your review is submitted successfully.',
    warningReviewBack: 'Are you sure? All unsaved changes will be lost',
    warningRateItem: 'How would you rate this item?',
    orderNum: 'Order #',
    orderID: 'Order ID: #{{id}}',
    status: 'Status',
    sku: 'SKU',
    noOrder: 'No orders placed',
    noOrderContent: 'Keep track of your orders here when you shop',
    viewDetails: 'View Details',
    shippingDetails: 'Shipping Details',
    billingDetails: 'Billing Address',
    shippingMethod: 'Shipping Method',
    paymentMethod: 'Payment Method',
    orderAgain: 'Order Again',
    warningMessage: 'Some products are invalid so they cannot be added to the shopping cart.',
    errorMessage: 'All products in this order are invalid so they cannot be added to the shopping cart.',
    content: 'Thanks for shopping with us',
    infoContent: 'You will receive a confirmation email shortly',
    viewOrder: 'View Order Details',
    backToHome: 'Back to Home',
    noAddress: 'No addresses saved',
    noAddressContent: 'Add an address to your account',
    aboveModalConfirm: 'Any unsaved changes will be lost',
    belowModalConfirm: 'Do you want to proceed?',
    saveChange: 'Save Changes',
    selectCountry: 'Select Country',
    Show_All: 'Show All',
    Pending: 'Pending',
    Cancelled: 'Cancelled',
    Shipped: 'Shipped',
    filterBy: 'Filter by',
    clearAll: 'Clear All',
    Newest_First: 'Newest First',
    Oldest_First: 'Oldest First',
    Lowest_Price_First: 'Lowest Price First',
    Highest_Price_First: 'Highest Price First',
    lowToHigh: 'Low To High',
    highToLow: 'High To Low',
    ascending: 'Ascending',
    descending: 'Descending',
    titleSort: 'Sort & Filter',
    resetAll: 'Reset All',
    sortBy: 'SORT BY',
    reset: 'Reset',
    sortToolBar: 'Sort',
    titleModalRate: 'Rate {{appName}}',
    remindMeLater: 'Remind me later',
    rateNow: 'Rate now',
    noThanks: 'No, thanks',
    contentModalRate: 'Would you mind taking a moment to rate {{appName}}? Thanks for your time and support!',
    titleSubjectMail: 'Device info for troubleshooting problem',
    warningRemoveAddress: 'Do you want to remove this address?',
    warningRemoveWishList: 'Do you want to remove this item from your wishlist?',
    warningRemoveShoppingCart: 'Do you want to remove this item from your shopping bag?',
    warningRemoveProduct: 'Do you want to delete the product?',
    textNo: 'No',
    textYes: 'Yes',
    textOK: 'OK',
    textClose: 'Close',
    textConfirm: 'Confirm',
    textContinue: 'Continue',
    textDone: 'Done',
    textDelete: 'Delete',
    textCancel: 'Cancel',
    inputText: 'Input text',
    requireFields: 'Please fill in all required fields',
    requireField: 'Required field',
    register: 'Register',
    errorRequired: '{{label}} is required',
    invalidEmail: 'Invalid Email Address',
    invalidFirstname: 'Invalid First Name',
    invalidLastname: 'Invalid Last Name',
    invalidConfirmPassword: 'Does not match password',
    emailFormHint: 'Please enter a valid email address',
    invalidConfirmEmail: 'Please enter the same value again',
    invalidPassword: 'Invalid Password',
    invalidPasswordCharacters: 'Passwords must be at least 7 characters and contain: lower case letters, upper case letters, at least 1 number, at least 1 special character',
    send: 'Send',
    firstName: 'First Name',
    lastName: 'Last Name',
    emailAddress: 'Email Address',
    confirmPassword: 'Confirm Password',
    generalInfo: 'General information',
    yourEmailAddress: 'Your email address',
    enterYourPassword: 'Enter a password',
    enterValidEmail: 'Enter a valid email',
    minCharacters: 'Min 8 characters',
    yourPassword: 'Your password',
    select: 'Select',
    textAddAddress: 'Add Address',
    headerRegister: 'Create new account',
    headerMyOrder: 'Order List',
    headerOrderDetails: 'Order Details',
    headerShoppingCart: 'Cart',
    headerEditAddress: 'Edit Address',
    headerNewAddress: 'Add Address',
    headerWishList: 'My Wishlist',
    headerNotifications: 'Notifications',
    headerDetail: 'Details',
    headerLocale: 'Select your language and currency',
    headerCountry: 'Select your country',
    headerLanguage: 'Select your language',
    headerSignUp: 'Create Account',
    noNotification: 'No notifications yet',
    noNotificationContent: 'Notifications from {{appName}} will show up here',
    titleErr: 'Error',
    noConnect: 'No internet connection',
    plsTryAgain: 'Please try again.',
    cantFindWay: "Can't find a way here.",
    matchField: 'Please match the requested format',
    minOrder: 'The minimum quantity allowed for purchase is {{minOrderQuantity}}',
    maxOrder: 'The maximum quantity allowed for purchase is {{maxOrderQuantity}}',
    errRegisterAppKey: 'Register app key {{appKey}} failed',
    invalidOrderId: 'Invalid orderId provided',
    noProduct: 'No recent products',
    noProductContent: 'Your recently viewed products will show up here',
};
