export default {
    textReturnListApp: 'Wilt u terugkeren naar de App-lijst?',
    appKey: 'App-sleutel',
    appName: 'App-naam',
    buildNumber: 'Buildnummer',
    deviceKey: 'Apparaatsleutel',
    notificationId: 'Notificatie-ID',
    deviceName: 'Apparaatnaam',
    osType: 'Besturingssysteemtype',
    sendMail: 'Mail versturen',
    recentlyViewed: 'Recent bekeken',
    createDate: 'Aanmaakdatum',
    searchAppPlaceHolder: 'Zoek app...',
    invalidAppKey: 'Ongeldige app-sleutel',
    enterAppKey: 'Voer uw app-sleutel in',
    allowRecivePush: 'Toegestaan om push te ontvangen',
    userEmail: 'Gebruikers e-mail',
    deviceInfo: 'Apparaat informatie',
    fcmToken: 'FCM-token',
    notificationDeviceId: 'Notificatie Apparaat-ID',
    apnsToken: 'Token APNS',
    switchAppKey: 'Wissel App-sleutel',
    buildText: 'Build',
    signIn: 'Inloggen',
    signUp: 'Registreren',
    logOut: 'Afmelden',
    buildVersion: 'Versie bouwen',
    doYouWantToLogOut: 'Wil je afmelden?',
    guestCheckout: 'Gast uitchecken',
    dontHaveAccount: 'Heb je geen account?',
    forgotPassword: 'Wachtwoord vergeten?',
    invalidAccount: 'Ongeldige gebruikersnaam en/of wachtwoord',
    deleteAccount: 'Account verwijderen',
    deleteSuccess: 'Account succesvol verwijderd',
    userSorry: 'Het spijt ons dat je vertrekt. Als je je account verwijdert',
    loseAccess: 'Je verliest de toegang tot je aankoopgeschiedenis',
    loseAllData: 'Je verliest alle gegevens geassocieerd met de app',
    ableAccess: 'Je kunt niet meer bij je verlanglijst',
    loginTitle: 'Oh! Je bent niet ingelogd {{appName}}',
    loginSubTitle: 'Dang nu in om uw bestellingen te volgen en te beheren.',
    signInLabel: 'Welkom bij {{appName}}',
    signInSubTitle: 'Dang nu in voor directe toegang tot uw gegevens, bestelgeschiedenis, retourzendingen en verlanglijstje.',
    followingInformation: 'Vul de volgende informatie in om je account te verwijderen',
    takeSomeTime: 'Aangezien dit proces handmatig is, kan het enige tijd duren voordat je account is verwijderd',
    confirmTitle: 'Weet je zeker dat je je account wilt verwijderen? (Dit kan niet ongedaan worden gemaakt)',
    contentDelete: 'Je accountverwijderingsverzoek is ingediend en wordt binnen enkele werkdagen verwerkt. \n' + '\n' + 'Je wordt zo snel mogelijk op de hoogte gebracht zodra het proces is voltooid. Als je van gedachten verandert, kun je altijd terugkomen en een nieuw account bij ons openen',
    contentForgotPassword: 'Laat ons alsjeblieft weten welk e-mailadres je hebt gebruikt om in te loggen en we sturen je een e-mail met instructies',
    noCatalog: 'Geen catalogus',
    shopAll: 'Shop alle',
    textOutOfStock: 'Sorry',
    outOfStock: 'Uit voorraad',
    addToCart: 'In winkelwagen',
    textUpdated: 'Bijgewerkt',
    noProduct: 'Geen producten beschikbaar',
    noProductContent: 'Laten we andere categorieën bekijken!',
    showPrice: 'Toon prijs',
    exceedMaxProductQty: 'You can only have "{{qty}}" of "{{productName}}" in your cart',
    item: 'Artikel',
    items: 'Artikelen',
    addedToCart: 'In winkelwagen',
    textOf: 'Van',
    textOpp: 'Oeps!',
    textNoLogin: 'Het lijkt erop dat je niet bent ingelogd, meld je aan om producten op te slaan in je favorieten.',
    freeShipping: 'Gratis verzending',
    buyNow: 'Koop nu',
    selectVariant: 'Variant selecteren',
    quantity: 'Hoeveelheid',
    weight: 'Gewicht',
    width: 'Breedte',
    height: 'Hoogte',
    depth: 'Diepte',
    upc: 'UPC',
    orderQuantityMinimum: 'Minimale aankoophoeveelheid',
    orderQuantityMaximum: 'Maximale aankoophoeveelheid',
    manufacturePartNumber: 'Manufacturer Part Number(MPN)',
    globalTradeItemNumber: 'Global Trade Item Number (GTIN)',
    binPickingNumber: 'Bin Picking Number (BPN)',
    inStock: 'Op voorraad',
    highStockMessage: '{{inventory}} in stock',
    lowStockMessage: 'Only {{inventory}} left',
     placeHolder: 'Producten zoeken',
    noRecentSearch: 'Geen recente zoekopdrachten',
    noRecentSearchContent: 'Uw recente zoekopdrachten verschijnen hier',
    searchHistory: 'Zoekgeschiedenis',
    noItemsFound: 'Geen items gevonden',
    noItemsFoundContent: 'Pas uw zoekopdracht aan en probeer het opnieuw',
    categories: 'Categorieën',
    products: 'Producten',
    seeAllResults: 'Bekijk alle resultaten',
    search: 'Zoeken',
    subTotal: 'Subtotaal',
    shipping: 'Verzending',
    tax: 'Belasting',
    discount: 'Korting',
    textCheckOut: 'Afrekenen',
    emptyCart: 'Uw winkelwagen is leeg',
    emptyCartContent: 'Laten we iets kopen!',
    invalidCoupon: 'Ongeldige Coupon',
    coupons: 'Couponcode',
    deleteProduct: 'Product verwijderen',
    textAdd: 'Toevoegen',
    textTypeVoucher: 'Voer couponcode in',
    couponDiscount: 'Korting',
    grandTotal: 'Totaalbedrag',
    selectVoucher: 'Coupon Code',
    total: 'Totaal',
    apply: 'Toepassen',
    noCoupon: 'Geen coupons',
    itemAddedToWatchList: 'Artikel is toegevoegd aan je verlanglijst',
    emptyWishlist: 'Je verlanglijstje is leeg',
    emptyWishlistContent: 'Tik op het hartpictogram om je favorieten op te slaan',
    loginWarning: 'Het lijkt erop dat je niet bent ingelogd, meld je aan om je favorieten op te slaan',
    textWriteReview: 'Schrijf een beoordeling',
    textBeFirstReview: 'Wees de eerste om dit product te beoordelen',
    titleReviewAlert: 'Beoordeling ingediend',
    topReviews: 'Topbeoordeling',
    viewAll: 'Bekijk alles',
    reviewSingle: '(1 beoordeling)',
    reviewMultiple: '({{count}} beoordelingen)',
    name: 'Naam',
    email: 'E-mail',
    reviewSubject: 'Beoordeling onderwerp',
    comments: 'Opmerkingen',
    allReview: 'Alle beoordelingen',
    reviewSubmitted: 'Uw beoordeling is succesvol ingediend.',
    warningReviewBack: 'Weet je het zeker? Alle niet-opgeslagen wijzigingen gaan verloren',
    warningRateItem: 'Hoe beoordeel je dit artikel?',
    orderNum: 'Bestel #',
    orderID: 'Bestel ID: #{{id}}',
    status: 'Status',
    sku: 'SKU',
    noOrder: 'U heeft geen bestellingen',
    noOrderContent: 'Doe hier navraag naar uw bestellingen wanneer u winkelt',
    viewDetails: 'Bekijk details',
    shippingDetails: 'Verzenddetails',
    billingDetails: 'Factuuradres',
    shippingMethod: 'Verzendmethode',
    paymentMethod: 'Betaalmethode',
    orderAgain: 'Bestel opnieuw',
    warningMessage: 'Sommige producten zijn ongeldig, dus ze kunnen niet aan het winkelwagentje worden toegevoegd.',
    errorMessage: 'Alle producten in deze bestelling zijn ongeldig, dus ze kunnen niet aan het winkelwagentje worden toegevoegd.',
    content: 'Bedankt voor het winkelen bij ons.',
    infoContent: 'Je ontvangt een bevestigingsmail van je bestelling met details van je bestelling en een link om de voortgang ervan te volgen.',
    viewOrder: 'Bekijk bestelgegevens',
    backToHome: 'Terug naar huis',
    noAddress: 'Geen adres',
    noAddressContent: 'Voeg een adres toe aan uw account toe',
    aboveModalConfirm: 'Alle niet-opgeslagen wijzigingen gaan verloren',
    belowModalConfirm: 'Wilt u doorgaan?',
    saveChange: 'Wijzigingen opslaan',
    selectCountry: 'Land selecteren',
    Show_All: 'Toon alles',
    Pending: 'In behandeling',
    Cancelled: 'Geannuleerd',
    Shipped: 'Verzonden',
    filterBy: 'Filteren op',
    clearAll: 'Wis alles',
    Newest_First: 'Nieuwste eerst',
    Oldest_First: 'Oudste eerst',
    Lowest_Price_First: 'Laagste prijs eerst',
    Highest_Price_First: 'Hoogste prijs eerst',
    lowToHigh: 'Laag Naar Hoog',
    highToLow: 'Hoog Naar Laag',
    ascending: 'Oplopend',
    descending: 'Aflopend',
    titleSort: 'Sorteer & Filter',
    resetAll: 'Alles opnieuw instellen',
    sortBy: 'SORTEREN OP',
    reset: 'Opnieuw instellen',
    sortToolBar: 'Sorteren',
    titleModalRate: 'Beoordeel {{appName}}',
    remindMeLater: 'Herinner me later',
    rateNow: 'Beoordeel nu',
    noThanks: 'Nee',
    contentModalRate: 'Zou je het erg vinden om een moment te nemen om {{appName}} te beoordelen? Bedankt voor je tijd en steun!',
    titleSubjectMail: 'Apparaat informatie voor probleemoplossing',
    warningRemoveAddress: 'Wilt u dit adres verwijderen?',
    warningRemoveWishList: 'Wil je dit item van je verlanglijst verwijderen?',
    warningRemoveShoppingCart: 'Wil je dit item uit je winkelwagen verwijderen?',
    warningRemoveProduct: 'Wilt u het product verwijderen?',
    textNo: 'Nee',
    textYes: 'Ja',
    textOK: 'OK',
    textClose: 'Sluiten',
    textConfirm: 'Bevestigen',
    textContinue: 'Doorgaan',
    textDone: 'Klaar',
    textDelete: 'Verwijderen',
    textCancel: 'Annuleren',
    inputText: 'Invoertekst',
    requireFields: 'Vul alle verplichte velden in',
    requireField: 'Verplicht veld',
    register: 'Registreren',
    errorRequired: '{{label}} is vereist',
    invalidEmail: 'Ongeldig e-mailadres',
    invalidFirstname: 'Ongeldige voornaam',
    invalidLastname: 'Ongeldige achternaam',
    invalidConfirmPassword: 'Komt niet overeen met wachtwoord',
    emailFormHint: 'Voer een geldig e-mailadres in',
    invalidConfirmEmail: 'Voer dezelfde waarde opnieuw in',
    invalidPassword: 'Ongeldig wachtwoord',
    invalidPasswordCharacters: 'Wachtwoorden moeten minimaal 7 tekens lang zijn en bevatten: kleine letters, hoofdletters, minstens 1 cijfer, minstens 1 speciaal teken',
    send: 'Verzenden',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    emailAddress: 'E-mailadres',
    confirmPassword: 'Bevestig wachtwoord',
    generalInfo: 'Algemene informatie',
    yourEmailAddress: 'Uw e-mailadres',
    enterYourPassword: 'Voer een wachtwoord in',
    enterValidEmail: 'Voer een geldig e-mailadres in',
    minCharacters: 'Min 8 tekens',
    yourPassword: 'Jouw wachtwoord',
    select: 'Selecteer',
    textAddAddress: 'Adres toevoegen',
     headerRegister: 'Maak een nieuw account aan',
    headerMyOrder: 'Mijn bestellingen',
    headerOrderDetails: 'Bestelgegevens',
    headerShoppingCart: 'Winkelwagen',
    headerEditAddress: 'Adres bewerken',
    headerNewAddress: 'Nieuw adres',
    headerWishList: 'Mijn verlanglijst',
    headerNotifications: 'Notificaties',
    headerDetail: 'Details',
    headerLocale: 'Selecteer uw taal en valuta',
    headerCountry: 'Selecteer uw land',
    headerLanguage: 'Kies uw taal',
    headerSignUp: 'Account aanmaken',
    noNotification: 'Nog geen meldingen',
    noNotificationContent: 'Meldingen van {{appName}} verschijnen hier',
    titleErr: 'Fout',
    noConnect: 'Geen internetverbinding',
    plsTryAgain: 'Probeer het opnieuw.',
    cantFindWay: 'Kan hier geen manier vinden.',
    matchField: 'Gelieve het gevraagde formaat aan te houden',
    minOrder: 'De minimumhoeveelheid voor aankoop is {{minOrderQuantity}}',
    maxOrder: 'De maximale hoeveelheid voor aankoop is {{maxOrderQuantity}}',
    errRegisterAppKey: 'Registratie van app-sleutel {{appKey}} mislukt',
    invalidOrderId: 'Ongeldige orderId verstrekt',
    noProduct: 'Geen recente producten',
    noProductContent: 'Hier worden je recent bekeken producten weergegeven',
}
